### ISSUE TITLE
Integration with sklearn

### ISSUE THREAD

**Issue by albertoazzari** [ysraell/random-forest-mc#4]
Hi, are you thinking of updating this classifier to integrate it with sklearn ?

**Comment by ysraell** [comment]
Yes! In TODO.md -> TODO Extras, I listed some actions to have a chance to do that. Certainly, will start in `contrib` mode. 
The Random Forest method and variations in Scikit-Learn is very well designed. There are a well structured chain of classes, turning able any custom variant preserving the framework standards. 

A possible strategy is:
1. Develop a version based on the Scikit-Learn basic classis, full compatible with the framework. Keep a standalone Python package.
2. Publish a article about the method. (important to have some confidence from other developers) 
3. Propose for enter the `contrib`.
4. Just wait if the method will be really used.

Sure, I have not so high expectations, the idea is to improve my dev skills. My method works very well with real problems, but I'm not thinking that method will be famous enough to be accepted to Scikit-Learn hall of the Random Forest models.
